# Generated by Django 2.1.4 on 2018-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0002_auto_20181206_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
