# Generated by Django 2.1.4 on 2018-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0003_auto_20181206_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
