# Generated by Django 2.1.4 on 2018-12-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0006_auto_20181206_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
