# Generated by Django 2.1.4 on 2018-12-06 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0007_media_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='added_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
