# Generated by Django 2.1.4 on 2018-12-07 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webadminpanel', '0009_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('number_of_screens', models.IntegerField(default=1)),
                ('geo_longitude', models.FloatField()),
                ('geo_latitude', models.FloatField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('street_number', models.CharField(max_length=20)),
                ('building_number', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Online'), (2, 'Offline'), (3, 'Connection lost')])),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, to='webadminpanel.Group')),
            ],
        ),
    ]
