# Generated by Django 2.1.4 on 2018-12-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0010_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
