# Generated by Django 2.1.4 on 2018-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0011_player_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'Offline'), (3, 'Connection lost')], default=2),
        ),
    ]
