# Generated by Django 2.1.4 on 2018-12-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0012_auto_20181207_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='building_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
