# Generated by Django 2.1.4 on 2018-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0013_auto_20181207_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
