# Generated by Django 2.1.4 on 2018-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadminpanel', '0014_auto_20181207_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='geo_latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='geo_longitude',
            field=models.FloatField(blank=True),
        ),
    ]
